#pragma once

enum
{
    USB_SUB_COMMAND_INIT = 1,
    USB_SUB_COMMAND_BEGIN_SET_ADDRESS = 2,
    USB_SUB_COMMAND_REMOTE_WAKEUP = 3,
    USB_SUB_COMMAND_CONNECT = 4,
    USB_SUB_COMMAND_DISCONNECT = 5,
    USB_SUB_COMMAND_SOF_ENABLE = 6,
    USB_SUB_COMMAND_SOF_DISABLE = 7,
    USB_SUB_COMMAND_EP_CLOSE_ALL = 8,
    USB_SUB_COMMAND_EP_STALL = 9,
    USB_SUB_COMMAND_EP_CLEAR_STALL = 10,
    USB_SUB_COMMAND_EP_CLOSE = 11,
    USB_SUB_COMMAND_FINISH_SET_ADDRESS = 12,
    USB_SUB_COMMAND_EP_OPEN = 13,
    USB_SUB_COMMAND_CLEAR_EVENT_QUEUE = 14,
    USB_SUB_COMMAND_DEINIT = 15,
    USB_SUB_COMMAND_BEGIN_TRANSFER = 16,
    USB_SUB_COMMAND_INTERRUPT_ENABLE = 17,
    USB_SUB_COMMAND_INTERRUPT_DISABLE = 18,
    USB_SUB_COMMAND_LOCAL_STACK = 19,
    USB_SUB_COMMAND_LOCAL_STACK_OFF = 20
};
